### ISSUE TITLE
Cannot find type definition file for 'core-js'

### ISSUE THREAD

**Issue by simonseyock** [500tech/angular2-tree-component#139]
Versions: 
angular2-tree-component: 2.7.0
angular2: 2.3.1

I tried to use the angular2-tree-component and got the following error message:
``node_modules\angular2-tree-component\dist\models\tree-node.model.d.ts:1:0 
Cannot find type definition file for 'core-js'.``

The solution for this was to remove the first line which is something like ``///reference types="core-js"``. After that it didn't report the error anymore.

**Comment by kleiinnn** [comment]
:+1: 
I encountered the same problem. Seems to work with version 2.6.0.

**Comment by sadplace** [comment]
yes, me too. there is a new line in "node_modules\angular2-tree-component\dist\models\tree-node.model.d.ts". This piece of code "/// <reference types="core-js" />"

This happens after i update angular to the latest version

**Comment by WillooWisp** [comment]
Same problem here, due to that reference!

**Comment by 123rajneesh** [comment]
If you upgrade angular 2 tree component then upgrade Typescript with latest version for visual studio and Visual Studio code.issue will resolve.

**Comment by schmuli** [comment]
I just had this issue too, and I looked at the source of the issue.

This could be resolved by specifying the `"lib"` option in `tsconfig.json`, using `["es2015", "dom"]`. And then you no longer need the `@types/core-js` dependency.

This will require everybody to use TypeScript >= 2.0, but I don't think is really an issue.

**Comment by Sevensnake** [comment]
@schmuli how did you fix it. specifying the lib?

**Comment by schmuli** [comment]
@Sevensnake The fix would need to be done in this repo, not the app using this.

As a potential workaround, you could try installing the `core-js` type definitions:

    npm install --save @types/core-js

I haven't tested this, so I can't guarantee this will work.

**Comment by manuelfink** [comment]
@schmuli I have core-js already included in the project thus includeing the core-j types just ends in more errors in reason of double definition.

**Comment by adamkleingit** [comment]
Hey @schmuli , thanks for the PR. I'll review shortly
